sbt/sbt-header

- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
This PR does not change anything to the inner working of the plugin, but provides an easier way to reference the keys that are used in the plugin, espcially in `.scala` builds.
The keys can now be imported with: `import de.heikoseeberger.sbtheader.HeaderKeys._`.
`import de.heikoseeberger.sbtheader.HeaderPlugin.autoImport._` still works.
> Move keys to their own object

- sbt-header-test/build.sbt
- src/main/scala/de/heikoseeberger/sbtheader/license/Apache2_0.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/Apache2_0Spec.scala
Allow variants of HeaderPattern for pre-canned Apache 2.0 license
> Allow variants of HeaderPattern for pre-canned Apache 2.0 license

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/license/License.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/BSD2ClauseSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/BSD3ClauseSpec.scala
Not sure if @fommil was kidding in #38, but here is a PR to add BSD 2 Clause and 3 Clause license. If we really want to add more popular licenses, I'd suggest adding GPL, LGPL and Eclipse License. That should cover most projects out there.
> BSD licenses

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/license/CommentBlock.scala
- src/main/scala/de/heikoseeberger/sbtheader/license/License.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/Apache2_0Spec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/BSD2ClauseSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/BSD3ClauseSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/GPLv3Spec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/LGPLv3Spec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/MITSpec.scala
- Changed implementation of License trait to be able to handle C++ style line comments
- Document built-in comment styles
Note: This PR includes one unrelated change: I've corrected wrong local variable names in the BSD specs.
> Implement C++ comment style for built-in Licenses

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/test/scala/de/heikoseeberger/sbtheader/CommentStyleMappingSpec.scala
As discussed in #44, it would be useful to have a convenience method that creates a mapping from file extension to License for common file extensions.
This PR introduces the CommentStyleMapping object with a single method: `createFrom(License, String, String)`. Currently the following file types are mapped by this method: scala, java, groovy, h, conf, properties, yml, sh.
After applying this PR, the following configuration:
```scala
import de.heikoseeberger.sbtheader.license.Apache2_0
headers := Map(
"scala" -> Apache2_0("2015", "Heiko Seeberger")
"conf" -> Apache2_0("2015", "Heiko Seeberger", "#")
)
```
can be changed to:
```scala
import de.heikoseeberger.sbtheader.license.Apache2_0
import de.heikoseeberger.sbtheader.CommentStyleMapping._
headers := createFrom(Apache2_0, "2015", "Heiko …
```
> Add comment style auto detection

- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/main/scala/de/heikoseeberger/sbtheader/license/CommentBlock.scala
- src/main/scala/de/heikoseeberger/sbtheader/license/License.scala
- src/test/scala/de/heikoseeberger/sbtheader/HeaderPluginSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/BSD3ClauseSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/GPLv3Spec.scala
- src/test/scala/de/heikoseeberger/sbtheader/license/LGPLv3Spec.scala
- This change provides the ability to use comments that look like:
/**
* License is here
*/
- Other changes were made by scalariform
> Allow for /** C-style comments

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/FileFilter.scala
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/excludes/project/test.sbt
- src/sbt-test/sbt-header/excludes/src/main/resources/Excluded.scala_expected
- src/sbt-test/sbt-header/excludes/src/main/resources/Included.scala_expected
- src/sbt-test/sbt-header/excludes/src/main/scala/Excluded.scala
- src/sbt-test/sbt-header/excludes/src/main/scala/Included.scala
- src/sbt-test/sbt-header/excludes/src/main/scala/de/heikoseeberger/allexcluded/Excluded.scala
- src/sbt-test/sbt-header/excludes/src/main/scala/de/heikoseeberger/allincluded/Included.scala
- src/sbt-test/sbt-header/excludes/src/main/scala/de/heikoseeberger/mixed/Excluded.scala
- src/sbt-test/sbt-header/excludes/src/main/scala/de/heikoseeberger/mixed/Included.scala
- src/sbt-test/sbt-header/excludes/test
- src/sbt-test/sbt-header/excludes/test.sbt
- src/test/scala/de/heikoseeberger/sbtheader/FileFilterSpec.scala
This is a fix for #30. It introduces a new settings key: `excludes` which is a Seq of strings denoting the file patterns to exclude. Users can specify glob patterns to exclude files form header creation. patterns may be relative to the project root.
> Fix #30: ability to ignore some files

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/checkHeaders-fails/project/test.sbt
- src/sbt-test/sbt-header/checkHeaders-fails/src/main/scala/HasHeader.scala
- src/sbt-test/sbt-header/checkHeaders-fails/src/main/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/checkHeaders-fails/test
- src/sbt-test/sbt-header/checkHeaders-fails/test.sbt
- src/sbt-test/sbt-header/checkHeaders/project/test.sbt
- src/sbt-test/sbt-header/checkHeaders/src/main/scala/HasHeader.scala
- src/sbt-test/sbt-header/checkHeaders/test
- src/sbt-test/sbt-header/checkHeaders/test.sbt
Fix for #57: Add task checkHeaders which will cause the build to fail in case there are files missing a header.
> #57: Task to verify the presence of headers

- README.md
- appveyor.yml
- src/sbt-test/sbt-header/simple/src/main/resources/HasHeader.scala_expected
- src/sbt-test/sbt-header/simple/src/main/resources/HasNoHeader.scala_expected
- src/sbt-test/sbt-header/simple/src/main/scala/HasHeader.scala
- src/sbt-test/sbt-header/simple/src/main/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/simple/test.sbt
Fix for #66 CI Build on Windows. Add an AppVeyor build definition. See https://ci.appveyor.com/project/britter/sbt-header how this will look like. To set this up, someone with access to the sbt organization has to login into AppVeyor and activate it for this repository. Further more the link in README.md has to be adjusted (you can copy paste it from the settings panel in AppVeyor).
> #66: Add AppVeyor build definition

- appveyor.yml
The default core.autocrlf for AppVeyor builds is input, see https://www.appveyor.com/docs/appveyor-yml/
GitHub documentation says one should use core.autocrlf = true on windows
machines, see https://help.github.com/articles/dealing-with-line-endings/#platform-windows
This could be a fix for #68. Waiting for the AppVeyor build to complete.
> Try to fix AppVeyor build.

- src/main/scala/de/heikoseeberger/sbtheader/CommentStyle.scala
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/main/scala/de/heikoseeberger/sbtheader/License.scala
- src/sbt-test/sbt-header/play-twirl/test.sbt
- src/test/scala/de/heikoseeberger/sbtheader/AGPLv3Spec.scala
- src/test/scala/de/heikoseeberger/sbtheader/Apache2_0Spec.scala
- src/test/scala/de/heikoseeberger/sbtheader/BSD2ClauseSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/BSD3ClauseSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/GPLv3Spec.scala
- src/test/scala/de/heikoseeberger/sbtheader/HeaderCommentStyleMappingSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/LGPLv3Spec.scala
- src/test/scala/de/heikoseeberger/sbtheader/MITSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/MPLv2Spec.scala
This is my initial approach to fix #78. This change makes the match in `License` exhausive and prepares the code for further refactorings. If this is the right direction, we should probably merge the `CommentStyles` with their respective `HeaderPattern` and `CommentBlock`.
> WIP: Introduce CommentStyle AST to make match in License exhausive (#78)

- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/main/scala/de/heikoseeberger/sbtheader/LicenseDetection.scala
- src/sbt-test/sbt-header/auto-detection/project/test.sbt
- src/sbt-test/sbt-header/auto-detection/src/main/resources/HasNoHeader.scala_expected
- src/sbt-test/sbt-header/auto-detection/src/main/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/auto-detection/test
- src/sbt-test/sbt-header/auto-detection/test.sbt
- src/sbt-test/sbt-header/checkHeaders-fails/test.sbt
- src/sbt-test/sbt-header/checkHeaders/test.sbt
- src/sbt-test/sbt-header/custom-license/test.sbt
- src/sbt-test/sbt-header/excludes/test.sbt
- src/sbt-test/sbt-header/play-twirl/test.sbt
- src/test/scala/de/heikoseeberger/sbtheader/LicenseDetectionSpec.scala
Fix for #73: Detect the project license based on the `licenses`, `organizationName` and `startYear` settings.
Note that `licenses` is of type `Seq((String, URL))`. The current implementation can only detect a license if `licenses` has only one entry. If there is exactly one entry the String has to contain a [SPDX license identifier](http://spdx.org/licenses/), which we than map to one of the licenses we support.
Users can still set the license directly by specifying the `headerLicense` setting. Is the `headerLicense` is set, it's value is given precedence.
> License auto-detection

- appveyor.yml
- src/main/scala/de/heikoseeberger/sbtheader/FileType.scala
- src/main/scala/de/heikoseeberger/sbtheader/HeaderCreator.scala
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/override-default-mappings/test.sbt
- src/sbt-test/sbt-header/play-twirl/test.sbt
- src/test/scala/de/heikoseeberger/sbtheader/HeaderCreatorSpec.scala
Fix for #101 and preparation for #90.
This introduces `FileType` as new abstraction. A `FileType` defines a file extension (e.g. `scala`) and an optional `Regex` matching a first line (for example a shebang line). If the `HeaderCreator` encounters a `FileType` with a first line matcher, it will preserve the first line, if one is found. This way we decouple first line detection from `HeaderCreator` at the cost of a slightly more verbose definition of `headerMappings`:
Before:
```scala
headerMappings := Map (
"scala" -> CStyleCommentBlock,
"java" -> CStyleCommentBlock
)
```
After:
```scala
headerMappings := Map (
HeaderFileType.scala -> CStyleCommentBlock,
HeaderFileType.java -> CStyleCommentBlock
)
```
> Introduce FileType as new abstraction allowing to specify header lines

- README.md
First draft of the documentation for the 2.0.0 release (fix for #79). I still need to work on the migration guide for users coming from 1.x version of the plugin.
> Rewrite of the documentation for 2.0.0 release

- src/main/scala/de/heikoseeberger/sbtheader/CommentStyle.scala
- src/test/scala/de/heikoseeberger/sbtheader/CommentStyleSpec.scala
Some repositories like Scala use special ASCII drawings where even special comment symbols are a part of art.
For example: 
```
/*                     __                                               *\
**     ________ ___   / /  ___     Scala API                            **
**    / __/ __// _ | / /  / _ |    (c) 2003-2013, LAMP/EPFL             **
**  __\ \/ /__/ __ |/ /__/ __ |    http://scala-lang.org/               **
** /____/\___/_/ |_/____/_/ | |                                         **
**                          |/                                          **
\*   
```
So I decided to add special CommentStyle which does not add any special character and instead just places the text that was accepted.
> Add IdentityCommentCreator that does not place any spacial characters.

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/CommentStyle.scala
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/override-default-mappings/test.sbt
- src/sbt-test/sbt-header/xml/test.sbt
- src/test/scala/de/heikoseeberger/sbtheader/CommentStyleSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/HeaderCreatorSpec.scala
There is no reason to configure comment styles using inheritance. It
easier to simply have one case class which can be configured via
constructor parameters.
This fixes #137.
> Make CommentStyle configurable.

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/CommentStyle.scala
- src/main/scala/de/heikoseeberger/sbtheader/HeaderCreator.scala
- src/test/scala/de/heikoseeberger/sbtheader/HeaderCreatorSpec.scala
Could be used to implement #23
Just a sketch for feedback, if the general approach looks OK I'll add tests and look more closely at binary compatibility.
> Allow project-specific CommentCreator taking into account the existing header

- README.md
I also noticed that file exclusion no longer works in 4.0.0, at least I could not get the example from the docs to work:
```
excludeFilter.in(unmanagedSources.in(headerCreate)) := HiddenFileFilter || "*Excluded.scala"
```
> Fix docs for supporting alternative configurations

- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/auto-detection/test
- src/sbt-test/sbt-header/custom-license/test
- src/sbt-test/sbt-header/excludes/test
- src/sbt-test/sbt-header/override-default-mappings/test
- src/sbt-test/sbt-header/simple/test
- src/sbt-test/sbt-header/xml/test
This fixes #149.
Note that I've updated most tests to make sure:
- `headerCheck` fails before headers are created
- `headerCheck` succeeds after headers are created
That's the most straightforward way I could think of testing for this change, but let me know if you have a better idea or mislike me messing with your tests.
> Have headerCheck and headerCreate work on the same files

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/excludes/test
- src/sbt-test/sbt-header/excludes/test.sbt
Fixes #130.
Provides a way to exclude sources from header creation without also excluding sources from compilation.
I believe the current setting - `excludeFilter.in(unmanagedSources.in(headerCreate))` - doesn't work because it flattens out to be the same as simply `excludeFilter.in(unmanagedSources)`. This will override the compilation path. To work around this I create several new named settings, allowing us to avoid the flattening. (Is there a better way?)
We could also leave it up to the user to use the `collectFiles(...)` method to do their own filtering, but I think this way is easier for users, so I defined `unmanagedSources.in(headerCreate)` to explicitly depend on its directories and filters.
I've tried a few different ways of doing this, and this is the best approach I could …
> Exclude sources from header creation, not compilation

- README.md
The fix is twofold:
* the way source works changed since the documentation was first written,
making it obsolete.
* the original documentation failed to add a comment style to template
files
> Fix sbt-boilerplate documentation

- README.md
This helps clarify that there are two different settings available for source files and resource files.
> Add an example of excluding from headerResources

- .travis.yml
- README.md
- build.sbt
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/incremental/project/test.sbt
- src/sbt-test/sbt-header/incremental/src/main/resources/HasHeader.scala_expected
- src/sbt-test/sbt-header/incremental/src/main/resources/HasHeader.scala_headerdropped
- src/sbt-test/sbt-header/incremental/src/main/resources/HasNoHeader.scala_expected
- src/sbt-test/sbt-header/incremental/src/main/scala/HasHeader.scala
- src/sbt-test/sbt-header/incremental/src/main/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/incremental/test
- src/sbt-test/sbt-header/incremental/test.sbt
Refs #168 
Nothing amazing but cuts a few seconds of a hot compile in the Akka project.
Didn't get any of the scripted tests to pass though, they log an error but scripted claims that tasks pass when they should fail.
> Incremental create headers using sbt cache infra

- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/incremental/test
- src/sbt-test/sbt-header/incremental/test.sbt
The previous cache incantation one would throw an exception when removing a file
previosly seen and modified by the createHeader.
> Bugfix: Use the right sbt cache API

- project/plugins.sbt
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/sbt-test/sbt-header/checkHeaders-all/project/test.sbt
- src/sbt-test/sbt-header/checkHeaders-all/src/main/scala/HasHeader.scala
- src/sbt-test/sbt-header/checkHeaders-all/src/test/scala/HasHeader.scala
- src/sbt-test/sbt-header/checkHeaders-all/test
- src/sbt-test/sbt-header/checkHeaders-all/test.sbt
- src/sbt-test/sbt-header/checkHeaders-fails-all/project/test.sbt
- src/sbt-test/sbt-header/checkHeaders-fails-all/src/main/scala/HasHeader.scala
- src/sbt-test/sbt-header/checkHeaders-fails-all/src/main/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/checkHeaders-fails-all/src/test/scala/HasHeader.scala
- src/sbt-test/sbt-header/checkHeaders-fails-all/src/test/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/checkHeaders-fails-all/test
- src/sbt-test/sbt-header/checkHeaders-fails-all/test.sbt
- src/sbt-test/sbt-header/simple-all/project/test.sbt
- src/sbt-test/sbt-header/simple-all/src/main/resources/HasHeader.scala_expected
- src/sbt-test/sbt-header/simple-all/src/main/resources/HasNoHeader.scala_expected
- src/sbt-test/sbt-header/simple-all/src/main/scala/HasHeader.scala
- src/sbt-test/sbt-header/simple-all/src/main/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/simple-all/src/test/resources/HasHeader.scala_expected
- src/sbt-test/sbt-header/simple-all/src/test/resources/HasNoHeader.scala_expected
- src/sbt-test/sbt-header/simple-all/src/test/scala/HasHeader.scala
- src/sbt-test/sbt-header/simple-all/src/test/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/simple-all/test
- src/sbt-test/sbt-header/simple-all/test.sbt
- Add two new tasks:
- `headerCreateAll`: Runs `headerCreate` in all available configurations
- `headerCheckAll`: Runs `headerCheck` in all available configurations
- Add scripted tests for both new tasks
> Add tasks to run `headerCreate` and `headerCheck` in all configurations

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/License.scala
- src/test/scala/de/heikoseeberger/sbtheader/LicenseDetectionSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/LicenseSpec.scala
The old indentifiers are deprecated as described in
https://www.gnu.org/licenses/identify-licenses-clearly.en.html
Fixes #178
> Add latest SPDX indentifiers for GNU licenses

- README.md
- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/main/scala/de/heikoseeberger/sbtheader/LicenseDetection.scala
- src/sbt-test/sbt-header/auto-detection-with-different-style/project/test.sbt
- src/sbt-test/sbt-header/auto-detection-with-different-style/src/main/resources/HasNoHeader.scala_expected
- src/sbt-test/sbt-header/auto-detection-with-different-style/src/main/scala/HasNoHeader.scala
- src/sbt-test/sbt-header/auto-detection-with-different-style/test
- src/sbt-test/sbt-header/auto-detection-with-different-style/test.sbt
- src/test/scala/de/heikoseeberger/sbtheader/LicenseDetectionSpec.scala
- Make `LicenseDetection` public so it can be used outside of this plugin, by third-party integrations.
- Change `LicenseDetection#startYear` to `String` so other values can be used (such as a year range).
- Add `LicenseStyle` parameter to `LicenseDetection`.
- Add new `headerLicenseStyle` setting to `HeaderPlugin` that `LicenseDetection` will use by default. It is backward compatible since the default value (`Detailed`) is also the default value of the different licenses constructors.
> Make `LicenseDetection` public and allow choosing license style

- src/main/scala/de/heikoseeberger/sbtheader/CommentStyle.scala
This would help if you want to have a header like
```
```
by using `LineCommentCreator("<--", "-->")`
What do you think?
> Allow adding suffix to LineCommentCreator

- src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
- src/test/scala/de/heikoseeberger/sbtheader/CommentStyleSpec.scala
- src/test/scala/de/heikoseeberger/sbtheader/HeaderCreatorSpec.scala
> Fix C++ and Hash styles with `headerEmptyLine := false`
