sbt/sbt-header

README.md, src/main/scala/de/heikoseeberger/sbtheader/SbtHeader.scala
=> Add some debug logging

src/main/scala/de/heikoseeberger/sbtheader/SbtHeader.scala
=> Change header patterns to avoid stack overflows (closes #6)

README.md, src/main/scala/de/heikoseeberger/sbtheader/SbtHeader.scala, src/main/scala/de/heikoseeberger/sbtheader/license/Apache2_0.scala, src/test/scala/de/heikoseeberger/sbtheader/license/Apache2_0Spec.scala
I am sure you don't want to support all licenses but as this repository is using Apache 2.0 license I thought that you might be more accepting of this PR which in turn would benefit me.
=> Addition of license classes

README.md, src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
Introduces a C++ comment style that is also found in protobuf files. Furthermore two new functions have been introduced in order to make it easier to express new types of block and line comment.
=> C++ comment style

.gitignore, src/main/scala/de/heikoseeberger/sbtheader/HeaderCreator.scala, src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala, src/test/scala/de/heikoseeberger/sbtheader/HeaderCreatorSpec.scala
This is a try to fix #24 line separators. Works well and pass tests on my environment.
=> Fix #24 Don't mess with line separators

src/main/scala/de/heikoseeberger/sbtheader/license/License.scala, src/test/scala/de/heikoseeberger/sbtheader/license/BSD2ClauseSpec.scala, src/test/scala/de/heikoseeberger/sbtheader/license/BSD3ClauseSpec.scala
As suggested by @fommil in #39
=> Fix indentation of BSD clauses

README.md, src/main/scala/de/heikoseeberger/sbtheader/license/License.scala, src/test/scala/de/heikoseeberger/sbtheader/license/GPLv3Spec.scala, src/test/scala/de/heikoseeberger/sbtheader/license/LGPLv3Spec.scala
As discussed in #38 and #39 here is a PR to add GPLv3 and LGPLv3.
=> Add GNU licenses

src/main/scala/de/heikoseeberger/sbtheader/license/License.scala, src/test/scala/de/heikoseeberger/sbtheader/license/MPLv2Spec.scala
=> Add Mozilla Public License 2.0 to the list of built-in licenses

project/build.properties
Update the sbt version used by the build from 0.13.9 to 0.13.12
=> Update the build to use the latest sbt version

README.md
Add badges for:
- Travis CI
- latest release on Bintray
- Apache License
=> Add more GitHub badges to README.md

README.md, src/main/scala/de/heikoseeberger/sbtheader/license/License.scala, src/test/scala/de/heikoseeberger/sbtheader/license/AGPLv3Spec.scala
This simply adds a template for using the AGPLv3 out of the box and tests for it.
=> Add template for AGPLv3

src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala, src/main/scala/de/heikoseeberger/sbtheader/License.scala, src/sbt-test/sbt-header/checkHeaders-fails/test.sbt, src/sbt-test/sbt-header/checkHeaders/test.sbt, src/sbt-test/sbt-header/custom-license/project/test.sbt, src/sbt-test/sbt-header/custom-license/src/main/resources/HasHeader.scala_expected, src/sbt-test/sbt-header/custom-license/src/main/resources/HasNoHeader.scala_expected, src/sbt-test/sbt-header/custom-license/src/main/scala/HasHeader.scala, src/sbt-test/sbt-header/custom-license/src/main/scala/HasNoHeader.scala, src/sbt-test/sbt-header/custom-license/test, src/sbt-test/sbt-header/custom-license/test.sbt, src/sbt-test/sbt-header/excludes/test.sbt, src/sbt-test/sbt-header/play-twirl/test.sbt, src/sbt-test/sbt-header/simple/test.sbt
=> Change settings to comment style per filetype but one license per project

src/main/scala/de/heikoseeberger/sbtheader/License.scala, src/main/scala/de/heikoseeberger/sbtheader/LicenseDetection.scala, src/sbt-test/sbt-header/checkHeaders-fails/test.sbt, src/sbt-test/sbt-header/checkHeaders/test.sbt, src/sbt-test/sbt-header/excludes/test.sbt, src/sbt-test/sbt-header/play-twirl/test.sbt, src/sbt-test/sbt-header/simple/test.sbt, src/test/scala/de/heikoseeberger/sbtheader/HeaderCommentStyleMappingSpec.scala, src/test/scala/de/heikoseeberger/sbtheader/LicenseDetectionSpec.scala, src/test/scala/de/heikoseeberger/sbtheader/LicenseSpec.scala
=> Rename Apache2_0 to ALv2

src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala, src/main/scala/de/heikoseeberger/sbtheader/License.scala, src/main/scala/de/heikoseeberger/sbtheader/LicenseDetection.scala, src/test/scala/de/heikoseeberger/sbtheader/LicenseDetectionSpec.scala
Partical fix for #93 addressing the first two tasks.
=> Rename Licenses trait to License and make it an object

src/main/scala/de/heikoseeberger/sbtheader/CommentStyle.scala, src/sbt-test/sbt-header/xml/project/test.sbt, src/sbt-test/sbt-header/xml/src/main/resources/order-header-no-xmldeclaration.xml, src/sbt-test/sbt-header/xml/src/main/resources/order-header-no-xmldeclaration.xml_expected, src/sbt-test/sbt-header/xml/src/main/resources/order-header-xmldeclaration.xml, src/sbt-test/sbt-header/xml/src/main/resources/order-header-xmldeclaration.xml_expected, src/sbt-test/sbt-header/xml/src/main/resources/order-no-header-no-xmldeclaration.xml, src/sbt-test/sbt-header/xml/src/main/resources/order-no-header-no-xmldeclaration.xml_expected, src/sbt-test/sbt-header/xml/src/main/resources/order-no-header-xmldeclaration.xml, src/sbt-test/sbt-header/xml/src/main/resources/order-no-header-xmldeclaration.xml_expected, src/sbt-test/sbt-header/xml/test, src/sbt-test/sbt-header/xml/test.sbt, src/test/scala/de/heikoseeberger/sbtheader/CommentStyleSpec.scala
=> WIP: Introduce XML comment style

src/sbt-test/sbt-header/play-twirl/project/build.properties
=> Remove build.properties from scripted test project.

src/main/scala/de/heikoseeberger/sbtheader/HeaderCreator.scala, src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala
Fixes #127 with little cleanup
=> Fix HeaderCreator leaking file descriptors

README.md, src/main/scala/de/heikoseeberger/sbtheader/HeaderCreator.scala, src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala, src/test/scala/de/heikoseeberger/sbtheader/HeaderCreatorSpec.scala
=> Opt-out of empty line between header and body

src/main/scala/de/heikoseeberger/sbtheader/CommentStyle.scala
=> Fix for compiling with JDK 11

project/plugins.sbt
Applying this PR will hopefully fix the publishing workflow (https://github.com/sbt/sbt-header/issues/268). The sbt-ci-release plugin was missing. Also removed some unused plugins and updated some things in the workflows.
=> Fix and update GitHub release action

build.sbt
fix https://github.com/sbt/sbt-header/issues/277
=> fix `publishMavenStyle` setting

src/main/scala/de/heikoseeberger/sbtheader/FileType.scala, src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala, src/sbt-test/sbt-header/no-file-extensions/project/test.sbt, src/sbt-test/sbt-header/no-file-extensions/src/main/resources/.routes, src/sbt-test/sbt-header/no-file-extensions/src/main/resources/.routes_expected, src/sbt-test/sbt-header/no-file-extensions/src/main/resources/more.routes, src/sbt-test/sbt-header/no-file-extensions/src/main/resources/more.routes_expected, src/sbt-test/sbt-header/no-file-extensions/src/main/resources/routes, src/sbt-test/sbt-header/no-file-extensions/src/main/resources/routes_expected, src/sbt-test/sbt-header/no-file-extensions/test, src/sbt-test/sbt-header/no-file-extensions/test.sbt, src/sbt-test/sbt-header/simple/src/main/resources/.routes, src/sbt-test/sbt-header/simple/src/main/resources/.routes_expected, src/sbt-test/sbt-header/simple/src/main/resources/.some.routes, src/sbt-test/sbt-header/simple/src/main/resources/.some.routes_expected, src/sbt-test/sbt-header/simple/src/main/resources/routes, src/sbt-test/sbt-header/simple/src/main/resources/routes_expected, src/sbt-test/sbt-header/simple/test.sbt
First I push a commit to update the current simple scripted test to see if my coming changes will not break backwards compatibility.
Update: That first commit [passed the tests](https://github.com/sbt/sbt-header/actions/runs/3272840586/jobs/5384329716)  :+1: 
Now I pushed the real "fix" and tests for it.
=> Support files without extensions / hidden files

src/main/scala/de/heikoseeberger/sbtheader/FileType.scala, src/test/scala/de/heikoseeberger/sbtheader/HeaderCreatorSpec.scala
=> StackOverflow for XML file
